### ISSUE TITLE
bug CFRP - about season - author 2 

### ISSUE THREAD

**Issue by saraharvey** [christopheryork/cfrp-analytics#6]
Impossible to request for any research author 2 and a particular season for example. 
Impossible to request season and pieces 1 and 2.
Need to request by evening (soirée) and season for example.

**Comment by christopheryork** [comment]
Resolved by revision to CFRP app's analytics web service.  

See commit https://github.com/hyperstudio/cfrp/commit/55c2a82f1291742ec56cf35ff93473c211fd53c5.
